name: Update Scholar Data

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '17 3 * * 1'  # weekly
  workflow_dispatch: {}    # enables Run workflow button

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scholarly

      - name: Fetch Google Scholar data
        env:
          PROFILE_ID: fQ_TTFsAAAAJ
          OUT_PATH: data/scholar.json
        run: |
          python scripts/fetch_scholar.py
          head -n 50 data/scholar.json || true

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): update scholar.json"
          file_pattern: data/scholar.json
